export default [
    {
      id: 1,
      title: "Collect Amazon package",
      description: "Text for details",
      price: 150,
      time: "14:00",
      author: "Jake",
    },
    {
      id: 2,
      title: "Complete assignment",
      description: "Computational Statistcs digital assignment",
      price: 500,
      time: "23:00",
      author: "Sheldon",
    },
    {
      id: 3,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Norm",
    },
    {
      id: 4,
      title: "Buy groceries",
      description: "Milk, almonds, honey, soya, bananas- a dozen, eggs- a crate",
      price: 500,
      time: "17:00",
      author: "Rosa",
    },
    {
      id: 5,
      title: "Deliver Package",
      description: "deliver a package to a student in N-block men's hostel. Contact for details",
      price: 200,
      time: "19:00",
      author: "Amy",
    },
    {
      id: 6,
      title: "Complete assignment",
      description: "Prepare an SRS documentation for the software Unitask",
      price: 800,
      time: "22:30",
      author: "Penny",
    },
    {
      id: 7,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Leonard",
    },
    {
      id: 8,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Rajesh",
    },
    {
      id: 9,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Howard",
    },
    {
      id: 10,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Charles",
    },
    {
      id: 11,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Terrance",
    },
    {
      id: 12,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Raymond",
    },
    {
      id: 13,
      title: "Buy groceries",
      description: "Milk",
      price: 500,
      time: "17:00",
      author: "Kevin",
    },
  ];
  